-- Disposable test schema setup only.
--
-- This file is for disposable Supabase validation runs only.
-- It creates minimal public tables needed by the Phase 3 readiness scripts.
-- It does not enable RLS, create policies, or enforce NOT NULL ownership.
-- It is safe to run after the account foundation migration has already been applied.

create table if not exists public.statuses (
  id bigint generated by default as identity primary key,
  name text,
  color text,
  type text,
  account_id uuid references accounts(id) on delete cascade
);

create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  first_name text,
  last_name text,
  email text,
  phone text,
  role text,
  status text,
  department text,
  title text,
  notes text,
  account_id uuid references accounts(id) on delete cascade
);

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  first_name text,
  last_name text,
  full_name text,
  email text,
  phone text,
  source text,
  status text,
  city text,
  state text,
  lead_score integer,
  assigned_agent text,
  notes text,
  account_id uuid references accounts(id) on delete cascade
);

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  first_name text,
  last_name text,
  full_name text,
  email text,
  phone text,
  status text,
  client_type text,
  assigned_agent text,
  notes text,
  account_id uuid references accounts(id) on delete cascade
);

create table if not exists public.invoices (
  id bigint generated by default as identity primary key,
  invoice_number text,
  client_id bigint references clients(id) on delete cascade,
  amount numeric,
  status text,
  due_date date,
  account_id uuid references accounts(id) on delete cascade
);

create table if not exists public.disputes (
  id bigint generated by default as identity primary key,
  client_id bigint references clients(id) on delete cascade,
  account_name text,
  account_number text,
  account_type text,
  bureau text,
  reason text,
  status text,
  round integer,
  bureau_response text,
  response_outcome text,
  response_date date,
  account_id uuid references accounts(id) on delete cascade
);

create table if not exists public.calendar_events (
  id bigint generated by default as identity primary key,
  title text,
  description text,
  date date,
  start_time text,
  end_time text,
  all_day boolean,
  type text,
  client_id bigint references clients(id) on delete cascade,
  assigned_agent text,
  location text,
  recurrence text,
  reminder text,
  color text,
  account_id uuid references accounts(id) on delete cascade
);

create table if not exists public.dispute_letters (
  id bigint generated by default as identity primary key,
  dispute_id bigint references disputes(id) on delete cascade,
  title text,
  content text,
  round integer,
  account_id uuid references accounts(id) on delete cascade
);

create table if not exists public.affiliates (
  id bigint generated by default as identity primary key,
  name text,
  company_name text,
  office_phone text,
  cell_phone text,
  email text,
  status text,
  start_date date,
  end_date date,
  commission text,
  account_id uuid references accounts(id) on delete cascade
);

create index if not exists statuses_account_id_idx on public.statuses(account_id);
create index if not exists employees_account_id_idx on public.employees(account_id);
create index if not exists leads_account_id_idx on public.leads(account_id);
create index if not exists clients_account_id_idx on public.clients(account_id);
create index if not exists invoices_account_id_idx on public.invoices(account_id);
create index if not exists disputes_account_id_idx on public.disputes(account_id);
create index if not exists calendar_events_account_id_idx on public.calendar_events(account_id);
create index if not exists dispute_letters_account_id_idx on public.dispute_letters(account_id);
create index if not exists affiliates_account_id_idx on public.affiliates(account_id);

